### ISSUE TITLE
Issues with examples on macOS 11.6.2

### ISSUE THREAD

**Issue by ghost** [padenot/monome-rs#5]
I'm getting the following when running the gradient, random examples :

```
Monome m29496721
	type: grid
	port: 11738
	host: 127.0.0.1
	id: m29496721
	prefix: /monome
	rotation: 0
	size: 16:8
thread 'tokio-runtime-worker-0' panicked at 'attempted to leave type `internal::Local` uninitialized, which is invalid', /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/internal.rs:493:59
stack backtrace:
   0:        0x10a6c2c11 - std::backtrace_rs::backtrace::libunwind::trace::h310ac7aacd577bf8
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10a6c2c11 - std::backtrace_rs::backtrace::trace_unsynchronized::had33a05577c9d011
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10a6c2c11 - std::sys_common::backtrace::_print_fmt::hd9acce3818e5f1bc
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10a6c2c11 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4edbddd26fc45697
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10a6dccbb - core::fmt::write::h266c957f12b1655a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:        0x10a6bd0da - std::io::Write::write_fmt::h65d4ee621e8d810d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:        0x10a6c4435 - std::sys_common::backtrace::_print::h9a5ef67cfa8b031e
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10a6c4435 - std::sys_common::backtrace::print::h99dfbbc518768f3b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10a6c4435 - std::panicking::default_hook::{{closure}}::h5b4886cd9f93dfca
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:        0x10a6c401f - std::panicking::default_hook::h986d152c7bd7e732
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:        0x10a6c4b20 - std::panicking::rust_panic_with_hook::h151f3b3bf37b4f17
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:        0x10a6c4594 - std::panicking::begin_panic_handler::{{closure}}::hf6660086d9ebd48c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
  12:        0x10a6c3087 - std::sys_common::backtrace::__rust_end_short_backtrace::h34152178ea368a9a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x10a6c452a - rust_begin_unwind
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  14:        0x10a6ea37f - core::panicking::panic_fmt::hb64a2db862b4aca0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  15:        0x10a6ea2d7 - core::panicking::panic::h709f8bbcee9c47c1
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
  16:        0x10a4dc157 - core::mem::uninitialized::h6ce35c06ca69e59d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/mem/mod.rs:665:9
  17:        0x10a4dc157 - <crossbeam_epoch::internal::Local as crossbeam_epoch::sync::list::IsElement<crossbeam_epoch::internal::Local>>::entry_of::h41dc8c101d72cc02
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/internal.rs:493:59
  18:        0x10a4e527c - crossbeam_epoch::sync::list::List<T,C>::insert::hb33c0ff264c39131
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/sync/list.rs:176:29
  19:        0x10a4db96c - crossbeam_epoch::internal::Local::register::h41cc96d83475147c
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/internal.rs:291:13
  20:        0x10a4dfc11 - crossbeam_epoch::collector::Collector::register::he9a90e7cd8b570ec
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/collector.rs:39:9
  21:        0x10a4e38e1 - crossbeam_epoch::default::HANDLE::__init::hb5d8ced5c4999ca9
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/default.rs:17:34
  22:        0x10a4e2e3d - core::ops::function::FnOnce::call_once::h806a63d939db16c3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  23:        0x10a4df82c - std::thread::local::lazy::LazyKeyInner<T>::initialize::ha67a20582e05b3e1
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:431:25
  24:        0x10a4decbe - std::thread::local::fast::Key<T>::try_initialize::hdec0b60aa9a38902
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:609:31
  25:        0x10a4dedd3 - std::thread::local::fast::Key<T>::get::h3cbdd412b1a6690b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:592:29
  26:        0x10a4895c9 - crossbeam_epoch::default::HANDLE::__getit::hf1f6e8bf5a21ddf3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:311:26
  27:        0x10a4ac994 - std::thread::local::LocalKey<T>::try_with::hf0e866558760e6a5
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:398:32
  28:        0x10a489330 - crossbeam_epoch::default::with_handle::hd59a8e193618c096
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/default.rs:42:5
  29:        0x10a4895ed - crossbeam_epoch::default::is_pinned::hc53516acaf3b3bf9
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.7.1/src/default.rs:29:5
  30:        0x10a4b2be3 - crossbeam_deque::Stealer<T>::steal_batch_and_pop::ha3dffd423d7fd13a
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-deque-0.7.1/src/lib.rs:933:12
  31:        0x10a4ae433 - tokio_threadpool::worker::entry::WorkerEntry::steal_tasks::hf7496a9d8808e9a0
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/entry.rs:207:9
  32:        0x10a4939cf - tokio_threadpool::worker::Worker::try_steal_task::h1a9950dd7b2db071
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:412:23
  33:        0x10a493306 - tokio_threadpool::worker::Worker::try_run_task::ha7a179d078b4976b
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:301:9
  34:        0x10a49316f - tokio_threadpool::worker::Worker::run::h0a0cc42f4c7f8edf
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:241:16
  35:        0x10a444a04 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h5aa3c5775578feab
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:381:33
  36:        0x10a448675 - tokio_trace_core::dispatcher::with_default::hf0ef78b3b2139bcf
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-trace-core-0.2.0/src/dispatcher.rs:64:5
  37:        0x10a444a31 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h1b0de6298e9c2f8a
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:380:29
  38:        0x10a448051 - tokio_timer::timer::handle::with_default::{{closure}}::h2fb6c57fa128a15b
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:101:9
  39:        0x10a43d38e - std::thread::local::LocalKey<T>::try_with::h6bc41cbed447c027
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  40:        0x10a43ca64 - std::thread::local::LocalKey<T>::with::hd6c8df96ea89aaf0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  41:        0x10a447e50 - tokio_timer::timer::handle::with_default::ha2e2b6940a54230a
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/timer/handle.rs:84:5
  42:        0x10a444a9a - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::hb2d4c1e501244d65
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:379:25
  43:        0x10a437881 - tokio_timer::clock::clock::with_default::{{closure}}::hfe88959ff00c1820
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:137:9
  44:        0x10a43d5aa - std::thread::local::LocalKey<T>::try_with::h97730529a10ab78c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  45:        0x10a43c9fb - std::thread::local::LocalKey<T>::with::hcd361bdf0cd47be1
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  46:        0x10a43760f - tokio_timer::clock::clock::with_default::hcc5ea9829c3318ed
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.11/src/clock/clock.rs:117:5
  47:        0x10a444adb - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::hac35495ed1d58dfa
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:378:21
  48:        0x10a445008 - tokio_reactor::with_default::{{closure}}::h5f0cc5fd7c7176c8
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237:9
  49:        0x10a43d172 - std::thread::local::LocalKey<T>::try_with::h651543479dc7e8e7
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  50:        0x10a43c99b - std::thread::local::LocalKey<T>::with::hbc7a120c2d3aabfa
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  51:        0x10a444d97 - tokio_reactor::with_default::hf781131e903ef803
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217:5
  52:        0x10a444b81 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h7d19b3a67fadac10
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.21/src/runtime/threadpool/builder.rs:377:17
  53:        0x10a4ad6ef - tokio_threadpool::callback::Callback::call::h231ed538ebae74f2
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/callback.rs:22:9
  54:        0x10a492e54 - tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::h133c21c3d072fd83
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:127:21
  55:        0x10a4909a2 - tokio_executor::global::with_default::{{closure}}::h98dda38f1a176dc2
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:209:9
  56:        0x10a4ac640 - std::thread::local::LocalKey<T>::try_with::h297d671374765b3a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  57:        0x10a4ac30c - std::thread::local::LocalKey<T>::with::hd2cc0ef56a8c3b0a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  58:        0x10a490888 - tokio_executor::global::with_default::hc15f6a386c26ca97
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:178:5
  59:        0x10a492f15 - tokio_threadpool::worker::Worker::do_run::{{closure}}::h6e862cc49678b30c
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:125:13
  60:        0x10a4ac723 - std::thread::local::LocalKey<T>::try_with::h5ac88f3dccb7061d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  61:        0x10a4ac205 - std::thread::local::LocalKey<T>::with::h0864bd437dba4e1f
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  62:        0x10a492d64 - tokio_threadpool::worker::Worker::do_run::h5feda49ea552559b
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/worker/mod.rs:116:9
  63:        0x10a49f6d6 - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h630c16e042be2816
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/pool/mod.rs:344:21
  64:        0x10a4b6080 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcaf5a277a20ff3f1
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:123:18
  65:        0x10a48a420 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hb008427d2353cdd4
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/mod.rs:483:17
  66:        0x10a4b6000 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h5406b4e9b1625283
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  67:        0x10a4a9409 - std::panicking::try::do_call::h5b5f11f61a028221
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  68:        0x10a4ac11d - <unknown>
                               at /Users/forrestbaer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.14/src/pool/backup_stack.rs:11:30
  69:        0x10a4a9334 - std::panicking::try::h623e419f7c55d014
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  70:        0x10a49c470 - std::panic::catch_unwind::h3fffef296551b711
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  71:        0x10a48a219 - std::thread::Builder::spawn_unchecked::{{closure}}::h304974c824f4d347
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/mod.rs:482:30
  72:        0x10a497171 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hda52a4a1a00a5233
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  73:        0x10a6c7327 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h37d47d53cf00472d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  74:        0x10a6c7327 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hab67b6cb96f82595
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  75:        0x10a6c7327 - std::sys::unix::thread::Thread::new::thread_start::h1ebadf8a3a1817e4
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  76:     0x7fff2059f8fc - __pthread_start
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
ERROR 2022-01-04T16:06:00Z: monome: Send channel disconnected
```

The enumerate examples work fine.. any idea why this could be happening?

**Comment by padenot** [comment]
I probably need to bump a couple of crates in version to pick bug fixes, one sec.

**Comment by ghost** [comment]
Yes it works fine after `cargo update`!

**Comment by ghost** [comment]
Very nice library by the way thank you for it!

**Comment by padenot** [comment]
1.1.3 has been published with the crate bumps, thanks for the kind words!
